using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace BasitBlogProjesi.Models
{
    public class BlogInitializer:DropCreateDatabaseIfModelChanges<VTContext>
    {
        protected override void Seed(VTContext context)
        {
            List<Category> kategoriler = new List<Category>() {
                new Category(){KategoriAdi="Sağlık"},
                new Category(){KategoriAdi="Teknoloji"},
                new Category(){KategoriAdi="Yaşam"},
                new Category(){KategoriAdi="Gündelik"},
                new Category(){KategoriAdi="Haber"},
                new Category(){KategoriAdi="Magazin"},

            };
            foreach (var item in kategoriler)
            {
                context.Kategoriler.Add(item);
            }
            context.SaveChanges();

            List<Blog> bloglar = new List<Blog>()
            {
                new Blog(){Baslik="Sağlıklı günler",Resim="1.jpg",Aciklama="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir",Icerik="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",Onay=true,Anasayfa=true,EklenmeTarihi=DateTime.Now.AddDays(-10),CategoryId=1},
                new Blog(){Baslik="Lorem ipsum dolor sit amet, consectetur adipiscing elit.",Resim="2.jpg",Aciklama="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultrices eleifend sapien eu rutrum. Etiam tristique, elit vitae dignissim elementum, mi felis volutpat diam, vitae tincidunt diam diam nec metus. Ut quis tortor et arcu hendrerit condimentum at at metus. Sed nec sodales sem. Curabitur malesuada arcu vitae posuere ultrices. Suspendisse posuere massa vitae nisi bibendum porttitor. Aliquam vitae nulla cursus, molestie arcu malesuada, hendrerit felis. Aliquam luctus faucibus ullamcorper. Nulla porta, dolor vel vulputate pretium, ante turpis molestie lectus, vitae sodales elit diam ac purus.",Onay=true,Anasayfa=true,EklenmeTarihi=DateTime.Now.AddDays(-10),CategoryId=2},
                new Blog(){Baslik="In sed ultricies felis. Proin dolor risus, feugiat et fermentum in",Resim="3.jpg",Aciklama="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir",Icerik="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultrices eleifend sapien eu rutrum. Etiam tristique, elit vitae dignissim elementum, mi felis volutpat diam, vitae tincidunt diam diam nec metus. Ut quis tortor et arcu hendrerit condimentum at at metus. Sed nec sodales sem. Curabitur malesuada arcu vitae posuere ultrices. Suspendisse posuere massa vitae nisi bibendum porttitor. Aliquam vitae nulla cursus, molestie arcu malesuada, hendrerit felis. Aliquam luctus faucibus ullamcorper. Nulla porta, dolor vel vulputate pretium, ante turpis molestie lectus, vitae sodales elit diam ac purus.",Onay=true,Anasayfa=true,EklenmeTarihi=DateTime.Now.AddDays(-10),CategoryId=3},
                new Blog(){Baslik="Fusce magna dui, faucibus vel ante in",Resim="4.jpg",Aciklama="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir",Icerik="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultrices eleifend sapien eu rutrum. Etiam tristique, elit vitae dignissim elementum, mi felis volutpat diam, vitae tincidunt diam diam nec metus. Ut quis tortor et arcu hendrerit condimentum at at metus. Sed nec sodales sem. Curabitur malesuada arcu vitae posuere ultrices. Suspendisse posuere massa vitae nisi bibendum porttitor. Aliquam vitae nulla cursus, molestie arcu malesuada, hendrerit felis. Aliquam luctus faucibus ullamcorper. Nulla porta, dolor vel vulputate pretium, ante turpis molestie lectus, vitae sodales elit diam ac purus.",Onay=true,Anasayfa=true,EklenmeTarihi=DateTime.Now.AddDays(-10),CategoryId=2},
                new Blog(){Baslik="Maecenas id dapibus nisi. Vivamus vitae hendrerit lorem",Resim="5.jpg",Aciklama="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir",Icerik="Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque ultrices eleifend sapien eu rutrum. Etiam tristique, elit vitae dignissim elementum, mi felis volutpat diam, vitae tincidunt diam diam nec metus. Ut quis tortor et arcu hendrerit condimentum at at metus. Sed nec sodales sem. Curabitur malesuada arcu vitae posuere ultrices. Suspendisse posuere massa vitae nisi bibendum porttitor. Aliquam vitae nulla cursus, molestie arcu malesuada, hendrerit felis. Aliquam luctus faucibus ullamcorper. Nulla porta, dolor vel vulputate pretium, ante turpis molestie lectus, vitae sodales elit diam ac purus.",Onay=true,Anasayfa=true,EklenmeTarihi=DateTime.Now.AddDays(-10),CategoryId=1},
                new Blog(){Baslik="Suspendisse pretium ac quam at maximus.",Resim="6.jpg",Aciklama="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir",Icerik="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",Onay=true,Anasayfa=true,EklenmeTarihi=DateTime.Now.AddDays(-10),CategoryId=1},
                new Blog(){Baslik="Sağlıklı günler",Resim="7.jpg",Aciklama="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir",Icerik="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",Onay=true,Anasayfa=true,EklenmeTarihi=DateTime.Now.AddDays(-10),CategoryId=2},
                new Blog(){Baslik="Sağlıklı günler",Resim="8.jpg",Aciklama="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir",Icerik="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",Onay=true,Anasayfa=true,EklenmeTarihi=DateTime.Now.AddDays(-10),CategoryId=3},
                new Blog(){Baslik="Sağlıklı günler",Resim="1.jpg",Aciklama="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir",Icerik="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",Onay=true,Anasayfa=true,EklenmeTarihi=DateTime.Now.AddDays(-10),CategoryId=4},
                new Blog(){Baslik="Sağlıklı günler",Resim="1.jpg",Aciklama="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir",Icerik="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",Onay=true,Anasayfa=true,EklenmeTarihi=DateTime.Now.AddDays(-10),CategoryId=5},
                new Blog(){Baslik="Sağlıklı günler",Resim="1.jpg",Aciklama="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir",Icerik="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",Onay=true,Anasayfa=true,EklenmeTarihi=DateTime.Now.AddDays(-10),CategoryId=5},
                new Blog(){Baslik="Sağlıklı günler",Resim="1.jpg",Aciklama="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir",Icerik="Lorem Ipsum, dizgi ve baskı endüstrisinde kullanılan mıgır metinlerdir. Lorem Ipsum, adı bilinmeyen bir matbaacının bir hurufat numune kitabı oluşturmak üzere bir yazı galerisini alarak karıştırdığı 1500'lerden beri endüstri standardı sahte metinler olarak kullanılmıştır. Beşyüz yıl boyunca varlığını sürdürmekle kalmamış, aynı zamanda pek değişmeden elektronik dizgiye de sıçramıştır. 1960'larda Lorem Ipsum pasajları da içeren Letraset yapraklarının yayınlanması ile ve yakın zamanda Aldus PageMaker gibi Lorem Ipsum sürümleri içeren masaüstü yayıncılık yazılımları ile popüler olmuştur.",Onay=true,Anasayfa=true,EklenmeTarihi=DateTime.Now.AddDays(-10),CategoryId=3},
            };
            foreach (var item in bloglar)
            {
                context.Bloglar.Add(item);
            }
            context.SaveChanges();

            base.Seed(context);
        }
    }
}